### ISSUE TITLE
Build error Duplicate class

### ISSUE THREAD

**Issue by pvdmde** [bambuser/BambuserPlayerSDK-Android#34]
When adding the current version of the library there is a build error.
We use protobuf-javalite-4.28.0 in our app.

Duplicate class com.google.protobuf.DescriptorProtos$UninterpretedOptionOrBuilder found in modules protobuf-javalite-4.28.0.jar -> protobuf-javalite-4.28.0 (com.google.protobuf:protobuf-javalite:4.28.0) and protolite-well-known-types-18.0.0.aar -> protolite-well-known-types-18.0.0-runtime (com.google.firebase:protolite-well-known-types:18.0.0)

I tried to exclude well-known-types to see if it is really used by bambuser. Yes it is:
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/type/LatLng;
	at com.google.firestore.v1.Value.dynamicMethod(Value.java:1806)
	at com.google.protobuf.GeneratedMessageLite.dynamicMethod(GeneratedMessageLite.java:290)

**Comment by zeyadsadaqa** [comment]
Hello @pvdmde, thanks for reaching out, we are going to look into it

**Comment by pvdmde** [comment]
Update:

+--- com.bambuser:player-sdk:1.3.2
\--- com.google.api.grpc:proto-google-common-protos:2.46.0
        \--- com.google.protobuf:protobuf-java:3.25.5

so bambuser's grps's -java and our -javalite dependencies collide

at the same time
 +--- com.bambuser:player-sdk:1.3.2
|    |    +--- com.google.firebase:firebase-firestore-ktx:24.10.1 -> 25.1.0
|    |    |    +--- com.google.firebase:firebase-firestore:25.1.0
...
+--- io.grpc:grpc-protobuf-lite:1.62.2
|    |    |    |    |    +--- io.grpc:grpc-api:1.62.2 (*)
|    |    |    |    |    +--- com.google.protobuf:protobuf-javalite:3.25.1 -> 4.28.2

pb-javalite is being pulled in by the sdk via grpc. This alone should conflict with itself, I'm not quite sure how it could would work even us not using -javalite in the app module.

I've tried so far to exclude the one and force the other, yielding the same error.

**Comment by pvdmde** [comment]
Update 2:
Looks like the problem is coming from and known at firebase.

See https://github.com/firebase/firebase-android-sdk/issues/5997

The workaround to downgrade protolite version seems to work so far.

**Comment by zeyadsadaqa** [comment]
Hello @pvdmde, I'm glad you found a temporary solution. Since we're under a tight deadline, if this issue is preventing you from working effectively, please reach out to our support team through your designated contact point. Let them know how urgent this matter is so we can prioritize it accordingly.
