### ISSUE TITLE
Crash when using Koin 3.5.0

### ISSUE THREAD

**Issue by SergioPoq** [bambuser/BambuserPlayerSDK-Android#8]
When using Koin 3.5.0, the app crashes when starts
It can be recreated on the Demo app adding `implementation("io.insert-koin:koin-android:3.5.0")` to the build.gradle file
```
FATAL EXCEPTION: main
Process: com.bambuser.liveshopping.player, PID: 5965
java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.NoSuchMethodError: No static method koinApplication(Lkotlin/jvm/functions/Function1;)Lorg/koin/core/KoinApplication; in class Lorg/koin/dsl/KoinApplicationKt; or its super classes (declaration of 'org.koin.dsl.KoinApplicationKt' appears in /data/app/~~-SNoHTZqxKMy1y68F84T-Q==/com.bambuser.liveshopping.player-RpAaaBuIR4QUNwtjAprVwA==/base.apk!classes7.dex)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7427)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6939)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6710)
	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: androidx.startup.StartupException: java.lang.NoSuchMethodError: No static method koinApplication(Lkotlin/jvm/functions/Function1;)Lorg/koin/core/KoinApplication; in class Lorg/koin/dsl/KoinApplicationKt; or its super classes (declaration of 'org.koin.dsl.KoinApplicationKt' appears in /data/app/~~-SNoHTZqxKMy1y68F84T-Q==/com.bambuser.liveshopping.player-RpAaaBuIR4QUNwtjAprVwA==/base.apk!classes7.dex)
	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2374)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7422)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6939) 
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6710) 
	at android.app.ActivityThread.access$1500(ActivityThread.java:247) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7839) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
Caused by: java.lang.NoSuchMethodError: No static method koinApplication(Lkotlin/jvm/functions/Function1;)Lorg/koin/core/KoinApplication; in class Lorg/koin/dsl/KoinApplicationKt; or its super classes (declaration of 'org.koin.dsl.KoinApplicationKt' appears in /data/app/~~-SNoHTZqxKMy1y68F84T-Q==/com.bambuser.liveshopping.player-RpAaaBuIR4QUNwtjAprVwA==/base.apk!classes7.dex)
	at com.bambuser.player.LVSPlayerActivityInitializer.create(SourceFile:25)
	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238) 
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206) 
	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45) 
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2404) 
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2374) 
	at android.app.ActivityThread.installProvider(ActivityThread.java:7422) 
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6939) 
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6710) 
	at android.app.ActivityThread.access$1500(ActivityThread.java:247) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7839) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 

```

**Comment by JennyBambuser** [comment]
The SDK is currently using an older version of Koin which is causing this issue, we will bump the version in an upcoming release.
If you need an urgent fix for this you could temporarily lower your version, `implementation("io.insert-koin:koin-android:3.4.3")` works in the demo app.
